# Generated by Django 3.1.1 on 2020-09-19 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1024)),
                ('number', models.CharField(max_length=16)),
                ('scheduled_at', models.DateTimeField(db_index=True, null=True)),
                ('expected_at', models.DateTimeField(null=True)),
                ('departure', models.TextField(db_index=True, null=True)),
                ('destination', models.TextField(db_index=True, null=True)),
                ('duration', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'flight',
                'index_together': {('departure', 'destination')},
            },
        ),
    ]
